### ISSUE TITLE
장바구니 수강신청 지원

### ISSUE THREAD

**Issue by voiciphil** [voiciphil/jbnu-macro#3]
- 장바구니 수강신청을 지원한다.

**Comment by Sabro98** [comment]
장바구니 수강신청은 학년이 필요 없으니까

장바구니 신청 시
`python main.py -n [학번] -p [비밀번호] -m[전공/장바구니 방법 선택] -i [과목 인덱스 (맨 위에서 0부터 시작)]`

으로 하고 전공을 선택했을 때 -g에 해당하는 학년 정보를 받게하는것은 어떤거요?
(+ 기존 -g argument의 required를 제거)

**Comment by voiciphil** [comment]
좋은 지적이고 안 그래도 염두하고 있었는데 지금 당장은 바꾸면 안 된다고 생각합니다.
장바구니 기능을 추가하면서 바꿔야 할 것 같습니다.
